Simple Backup Cash Shell Script
Note: 
#!/bin/bash
tar -czf /tmp/myhome_directory.tar.gz /home/linuxconfig
DOES NOT WORK IN GIT BASH TERMINAL.

Alternative Solution: $ git archive -o test.tar.gz master

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$  tar -czf /tmp/myhome_directory.tar.gz /OneDrive/Desktop/Java II/git/Project02
tar: Removing leading `/' from member names
tar: /OneDrive/Desktop/Java: Cannot stat: No such file or directory
tar: II/git/Project02: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$  tar -czf /tmp/myhome_directory.tar.gz /Project02
tar: Removing leading `/' from member names
tar: /Project02: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$  tar -czf /tmp/myhome_directory.tar.gz /home/linuxconfig/
tar: Removing leading `/' from member names
tar: /home/linuxconfig: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git archive -o test.tar master

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ which bash > backup.sh

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ ;s -1
bash: syntax error near unexpected token `;'

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ ls -1
0_xvz
backup.sh
Bash*
date.sh*
hello-world.sh*
README.md
task.sh
test.tar

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ echo git archive -o test.tar master
git archive -o test.tar master

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ nano backup.sh

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git commit -m "backup.sh"
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        backup.sh
        test.tar

nothing added to commit but untracked files present (use "git add" to track)

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git add backup.sh
warning: LF will be replaced by CRLF in backup.sh.
The file will have its original line endings in your working directory

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git commit -m "Simple Backup Bash Shell Script"
[master 214b5cf] Simple Backup Bash Shell Script
 1 file changed, 3 insertions(+)
 create mode 100644 backup.sh

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git branch -M master

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git push -u master origin
error: src refspec origin does not match any
error: failed to push some refs to 'master'

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git push -u origin master
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 352 bytes | 352.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/Brenzo94/Project02.git
   482c2fe..214b5cf  master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.