File Names and Permissions Resoled Merge Errors
btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ echo "#Project02" >> hello-world.sh

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git init
Reinitialized existing Git repository in C:/Users/btlbh/OneDrive/Desktop/Java II/git
/Project02/.git/

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git add hello-world.sh
warning: LF will be replaced by CRLF in hello-world.sh.
The file will have its original line endings in your working directory

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ nano hello-world.sh

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git commit -m "hello-world"
[master ecde3c7] hello-world
 1 file changed, 2 deletions(-)

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git branch -M master

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git push -u origin master
To https://github.com/Brenzo94/Project02.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/Brenzo94/Project02.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git pull origin master
From https://github.com/Brenzo94/Project02
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
        task.sh
Please commit your changes or stash them before you merge.
Aborting

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git add -A
warning: LF will be replaced by CRLF in hello-world.sh.
The file will have its original line endings in your working directory

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git pull origin master
From https://github.com/Brenzo94/Project02
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
  hello-world.sh task.sh

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git add -A && git commit -m "hello-world"
[master 37e897d] hello-world
 2 files changed, 3 insertions(+), 4 deletions(-)

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git branch -M master

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git push -u origin master
To https://github.com/Brenzo94/Project02.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/Brenzo94/Project02.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git pull
Auto-merging task.sh
CONFLICT (content): Merge conflict in task.sh
Automatic merge failed; fix conflicts and then commit the result.

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master|MERGING)
$ git status
On branch master
Your branch and 'origin/master' have diverged,
and have 4 and 5 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:
        modified:   Bash

Unmerged paths:
  (use "git add <file>..." to mark resolution)
        both modified:   task.sh


btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master|MERGING)
$ git add task.sh

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master|MERGING)
$ git commit -m "task.sh"
[master 62d5fe7] task.sh

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git branch -M master

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git push -u origin master
Enumerating objects: 18, done.
Counting objects: 100% (18/18), done.
Delta compression using up to 8 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (14/14), 1.43 KiB | 733.00 KiB/s, done.
Total 14 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), done.
To https://github.com/Brenzo94/Project02.git
   7e99e1f..62d5fe7  master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.