Hello World Bash Shell Script
Note: Initial push of the updated Hello-World Bash Shell Script was rejected. I used the "git add -A && git commit -m "date.sh"" command to merge and commit my files and then pull them from my GitHub repository to resolve this issue.
Terminal Output:
btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ which bash > hello-world.sh

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ nano hello-world.sh

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ chmod +x hello-world.sh

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ ./hello-world.sh
Hello World

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git add hello-world.sh
warning: LF will be replaced by CRLF in hello-world.sh.
The file will have its original line endings in your working directory

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git commit -m "Hello World Bash Shell Script"
[master bfc35eb] Hello World Bash Shell Script
 1 file changed, 1 insertion(+), 1 deletion(-)

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git branch -M master

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git push -u origin master
To https://github.com/Brenzo94/Project02.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/Brenzo94/Project02.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git pull origin master
From https://github.com/Brenzo94/Project02
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
        date.sh
Please commit your changes or stash them before you merge.
Aborting

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git add -A && git commit -m "date.sh"
warning: LF will be replaced by CRLF in date.sh.
The file will have its original line endings in your working directory
[master cfb6fe8] date.sh
 1 file changed, 3 insertions(+), 1 deletion(-)

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git push -u origin master
To https://github.com/Brenzo94/Project02.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/Brenzo94/Project02.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git pull origin master
From https://github.com/Brenzo94/Project02
 * branch            master     -> FETCH_HEAD
Merge made by the 'recursive' strategy.

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ ./hello-world.sh
Hello World

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git add hello-world.sh

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git commit -m "Hello-World Bash Shell Script"
On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)
$ git push -u origin master
Enumerating objects: 10, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 657 bytes | 328.00 KiB/s, done.
Total 6 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 1 local object.
To https://github.com/Brenzo94/Project02.git
   fa4b89c..8ef91fe  master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.

btlbh@DESKTOP-I5H5FMG MINGW64 ~/OneDrive/Desktop/Java II/git/Project02 (master)